/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-07-26 07:30:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jettjia.util.CookieUtil;

public final class product_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<title>会员登录</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\" />\r\n");
      out.write("\t\t<script src=\"js/jquery-1.11.3.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<!-- 引入自定义css文件 style.css -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\tbody {\r\n");
      out.write("\t\t\t\tmargin-top: 20px;\r\n");
      out.write("\t\t\t\tmargin: 0 auto;\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.carousel-inner .item img {\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\theight: 300px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("            \t时间：2015-12-30\r\n");
      out.write("            \t描述：菜单栏\r\n");
      out.write("            -->\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/logo2.png\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/header.png\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\" style=\"padding-top:20px\">\r\n");
      out.write("\t\t\t\t\t<ol class=\"list-inline\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.htm\">登录</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"register.htm\">注册</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"cart.htm\">购物车</a></li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("            \t时间：2015-12-30\r\n");
      out.write("            \t描述：导航条\r\n");
      out.write("            -->\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navbar-brand\" href=\"#\">首页</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"product_list.jsp\">手机数码<span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">电脑办公</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">电脑办公</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">电脑办公</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"navbar-form navbar-right\" role=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.container-fluid -->\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\" style=\"width:1210px;margin:0 auto;\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">首页</a></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"ProductInfoServlet?id=1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10001.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"ProductInfoServlet?id=1\" style='color:green'>冬瓜</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"ProductInfoServlet?id=2\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10002.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>圆白菜</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"ProductInfoServlet?id=3\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10003.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>甜玉米</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"ProductInfoServlet?id=4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10004.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>胡萝卜</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"product_info.htm\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10005.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>芹菜</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"product_info.htm\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10006.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>韭菜</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"product_info.htm\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10007.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>香菜</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"product_info.htm\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10008.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>土豆</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"product_info.htm\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10007.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>香菜</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"product_info.htm\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10008.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>土豆</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"product_info.htm\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10007.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>香菜</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<a href=\"product_info.htm\">\r\n");
      out.write("\t\t\t\t\t<img src=\"products/1/cs10008.jpg\" width=\"170\" height=\"170\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p><a href=\"product_info.html\" style='color:green'>土豆</a></p>\r\n");
      out.write("\t\t\t\t<p><font color=\"#FF0000\">商城价：&yen;299.00</font></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--分页 -->\r\n");
      out.write("\t\t<div style=\"width:380px;margin:0 auto;margin-top:50px;\">\r\n");
      out.write("\t\t\t<ul class=\"pagination\" style=\"text-align:center; margin-top:10px;\">\r\n");
      out.write("\t\t\t\t<li class=\"disabled\"><a href=\"#\" aria-label=\"Previous\"><span aria-hidden=\"true\">&laquo;</span></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">6</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">7</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">8</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">9</a></li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 分页结束=======================        -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--\r\n");
      out.write("       \t\t商品浏览记录:\r\n");
      out.write("        -->\r\n");
      out.write("\t\t<div style=\"width:1210px;margin:0 auto; padding: 0 9px;border: 1px solid #ddd;border-top: 2px solid #999;height: 246px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h4 style=\"width: 50%;float: left;font: 14px/30px \" 微软雅黑 \";\">浏览记录</h4>\r\n");
      out.write("\t\t\t<div style=\"width: 50%;float: right;text-align: right;\"><a href=\"\">more</a></div>\r\n");
      out.write("\t\t\t<div style=\"clear: both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"overflow: hidden;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t");
 
						// 获得cookie
						Cookie[] cookies = request.getCookies();
						// 获得记录history的cookie对象
						Cookie cookie = CookieUtil.findCookie(cookies, "history");
						// 没有访问记录
						if (cookie == null) {
					
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<h2>浏览记录为空！！！</h2>\r\n");
      out.write("\t\t\t\t\t");
	
						} else {
							// 有访问记录
							String[] ids = cookie.getValue().split("#");
							for (String id : ids) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"width: 150px;height: 216;float: left;margin: 0 8px 0 0;padding: 0 18px 15px;text-align: center;\"><img src=\"products/1/cs1000");
      out.print(id );
      out.write(".jpg\" width=\"130px\" height=\"130px\" /></li>\r\n");
      out.write("\t\t\t\t\t");
			
							}
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<h2><a href=\"ClearHistory\">清除浏览记录</a></h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"margin-top:50px;\">\r\n");
      out.write("\t\t\t<img src=\"./image/footer.jpg\" width=\"100%\" height=\"78\" alt=\"我们的优势\" title=\"我们的优势\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"text-align: center;margin-top: 5px;\">\r\n");
      out.write("\t\t\t<ul class=\"list-inline\">\r\n");
      out.write("\t\t\t\t<li><a>关于我们</a></li>\r\n");
      out.write("\t\t\t\t<li><a>联系我们</a></li>\r\n");
      out.write("\t\t\t\t<li><a>招贤纳士</a></li>\r\n");
      out.write("\t\t\t\t<li><a>法律声明</a></li>\r\n");
      out.write("\t\t\t\t<li><a>友情链接</a></li>\r\n");
      out.write("\t\t\t\t<li><a target=\"_blank\">支付方式</a></li>\r\n");
      out.write("\t\t\t\t<li><a target=\"_blank\">配送方式</a></li>\r\n");
      out.write("\t\t\t\t<li><a>服务声明</a></li>\r\n");
      out.write("\t\t\t\t<li><a>广告声明</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"text-align: center;margin-top: 5px;margin-bottom:20px;\">\r\n");
      out.write("\t\t\tCopyright &copy; 2005-2016 传智商城 版权所有\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
